services:
  backend:
    build: .
    image: employee-directory-img

    ports:
      - "8080:8080"

    environment:
      DB_USERNAME: root
      DB_PASSWORD: root
      GOOGLE_CLIENT_ID: 905237510600-5sc43n0mp8okmdn4hv9oi6bmhj8kv8cs.apps.googleusercontent.com